version: '3.5'
services:
  wakeup:
    container_name: wakeup
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./wakeup-cache:/opt/wakeup/wakeup-cache
